# Generated by Django 2.2.5 on 2020-11-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userprofile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], null=True),
        ),
    ]
