# Generated by Django 2.2.5 on 2020-11-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20201112_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleinfo',
            old_name='articletag',
            new_name='tag',
        ),
    ]
