# Generated by Django 2.2.5 on 2020-11-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20201112_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleinfo',
            old_name='tag',
            new_name='artitag',
        ),
    ]
