# Generated by Django 2.2.5 on 2020-11-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20201112_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='tag',
            field=models.CharField(blank=True, max_length=500, verbose_name='标签'),
        ),
    ]
