# Generated by Django 2.2.5 on 2020-11-13 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_auto_20201112_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='bottle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zhuangtai', models.IntegerField(default=0, max_length=10, verbose_name='瓶子的状态')),
                ('getuser', models.CharField(blank=True, max_length=100, null=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleInfo', verbose_name='所属瓶子文字')),
                ('postuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布用户')),
            ],
            options={
                'verbose_name': '瓶子状态',
            },
        ),
    ]
