# Generated by Django 2.2.5 on 2020-11-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_bottle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='zhuangtai',
            field=models.IntegerField(default=0, verbose_name='瓶子的状态'),
        ),
    ]
