# Generated by Django 2.2.5 on 2020-11-14 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20201114_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Comment'),
        ),
    ]
